from typing import List
from claw_ast import Program, BlockDefinition, GenericLineBlock, GotoBlock, BackBlock, BlockContent
from claw_lexer import Token, TokenType

class Parser:
    """
    Parses a list of tokens generated by the Lexer into an Abstract Syntax Tree (AST).
    """
    def __init__(self, tokens: List[Token]):
        self.tokens = tokens
        self.current_token_index = 0

    @property
    def current_token(self) -> Token:
        """Returns the current token without consuming it."""
        if self.current_token_index < len(self.tokens):
            return self.tokens[self.current_token_index]
        else:
            # If index is out of bounds, return the EOF Token (guaranteed by Lexer).
            return self.tokens[-1]

    def peek(self, offset: int = 1) -> Token:
        """
        Look ahead at upcoming tokens without consuming them.
        Returns the EOF token if the offset goes out of bounds.
        """
        index = self.current_token_index + offset
        if index < len(self.tokens):
            return self.tokens[index]
        else:
            # Out of bounds
            return self.tokens[-1]

    def consume(self, *expected_types: TokenType) -> Token:
        """
        Consumes the current token, advances the parser,
        and checks if the consumed token's type is among the expected types.
        Raises a SyntaxError if the type does not match.
        """
        current = self.current_token
        if not expected_types or current.type in expected_types: # Allow consuming any token if no types are specified
            if current.type != TokenType.EOF: # Avoid advancing past EOF
                 self.current_token_index += 1
            return current
        else:
            self.error(f"Expected one of {expected_types}, but got {current.type} ('{current.lexeme}')")

    def error(self, message: str):
        """Raises a SyntaxError with context information."""
        token = self.current_token
        raise SyntaxError(f"Syntax Error at line {token.line}, column {token.column}: {message}. Current token: {token}")

    # --- Parsing Entry Point ---
    def parse(self) -> Program:
        """Parses the entire token stream into a Program AST node."""
        program_node = self.parse_program()
        # Ensure we consume all tokens up to EOF.
        self.consume(TokenType.EOF)
        return program_node

    # --- Top-level rule: Program ---
    def parse_program(self) -> Program:
        """Parses the top-level structure: a sequence of BlockDefinitions."""
        program_node = Program()

        # Skip any leading newlines before the first block definition.
        self._skip_newline()

        # Main parsing loop: expect block definitions until EOF.
        while self.current_token.type != TokenType.EOF:
            if self.current_token.type == TokenType.AT:
                block_def = self.parse_block_definition()
                program_node.block_definitions.append(block_def)
                # Skip potential newlines between block definitions.
                self._skip_newline()
            else:
                # Enforce that programs must contain block definitions.
                self.error("Expected Block Definition starting with '@' or End of File.")

        return program_node

    # --- Parse a Block Definition ---
    def parse_block_definition(self) -> BlockDefinition:
        """Parses a block definition: @ IDENTIFIER : NEWLINE { content }."""
        # Syntax: @ IDENTIFIER :
        self.consume(TokenType.AT)
        name_token = self.consume(TokenType.IDENTIFIER)
        self.consume(TokenType.COLON)

        block_node = BlockDefinition(name=name_token.value)

        # Expect content or newlines after the colon.
        self._skip_newline()

        # Parse lines within the block until the next block definition ('@') or EOF.
        while self.current_token.type != TokenType.AT and \
              self.current_token.type != TokenType.EOF:

            # Skip any blank lines within the block.
            self._skip_newline()

            # Check again after skipping newlines, in case we hit the end.
            if self.current_token.type == TokenType.AT or self.current_token.type == TokenType.EOF:
                break

            # Determine the type of statement on the current line.
            first_token_on_line = self.current_token

            if first_token_on_line.type == TokenType.KEYWORD_GOTO:
                goto_block = self.parse_goto_block()
                block_node.inner_content.append(goto_block)
            elif first_token_on_line.type == TokenType.KEYWORD_BACK:
                back_block = self.parse_back_block()
                block_node.inner_content.append(back_block)
            elif first_token_on_line.type == TokenType.KEYWORD_INT:
                 # V1: Simply skip variable declaration lines entirely.
                self._skip_variable_declaration()
            # TODO: Add label parsing if needed:
            # elif first_token_on_line.type == TokenType.IDENTIFIER and self.peek(1).type == TokenType.COLON:
            #     pass # Implement parse_label_block if needed
            else:
                # Treat other lines as generic statements (assignments, calls, etc.).
                generic_line_block = self.parse_generic_line_block()
                block_node.inner_content.append(generic_line_block)

        return block_node

    # --- Helper to skip whitespace ---
    def _skip_newline(self):
        """Skips any consecutive NEWLINE tokens."""
        while self.current_token.type == TokenType.NEWLINE:
            self.consume(TokenType.NEWLINE)

    # --- Parse Generic Line Block (e.g., assignment, print) ---
    def parse_generic_line_block(self) -> GenericLineBlock:
        """Parses a line of code that isn't a specific keyword statement."""
        # Collect all tokens on the current line until NEWLINE, '@', or EOF.
        line_tokens = []
        current_line = self.current_token.line

        # Loop to collect tokens belonging to the current logical line.
        while self.current_token.line == current_line and \
              self.current_token.type not in (TokenType.NEWLINE, TokenType.AT, TokenType.EOF):

             # Explicitly skip leading SPACE tokens on the line, though Lexer might handle most.
             if self.current_token.type == TokenType.SPACE:
                  self.consume(TokenType.SPACE)
                  continue # Skip space, do not add to line_tokens

             line_tokens.append(self.current_token)
             self.consume(self.current_token.type) # Consume the token after adding it.

        # IMPORTANT: Consume the trailing NEWLINE if present to advance past the line.
        if self.current_token.type == TokenType.NEWLINE:
             self.consume(TokenType.NEWLINE)

        # Create and return the GenericLineBlock node.
        # Raw text could be reconstructed here if needed:
        # raw_text = "".join(t.lexeme for t in line_tokens)
        return GenericLineBlock(line_tokens=line_tokens)

    # --- Parse Goto Block ---
    def parse_goto_block(self) -> GotoBlock:
        """Parses a 'goto IDENTIFIER' statement."""
        self.consume(TokenType.KEYWORD_GOTO)
        target_token = self.consume(TokenType.IDENTIFIER)

        # Expect a newline or EOF after the goto statement.
        self._consume_newline_or_eof("after goto statement")

        return GotoBlock(target_block_name=target_token.value)

    # --- Parse Back Block ---
    def parse_back_block(self) -> BackBlock:
        """Parses a 'back' statement."""
        self.consume(TokenType.KEYWORD_BACK)
        
        # Expect a newline or EOF after the back statement.
        self._consume_newline_or_eof("after back statement")

        return BackBlock()

    # --- Helper to consume NEWLINE after a line block ---
    def _consume_newline_or_eof(self, context: str):
         """Consumes a required NEWLINE, or checks for EOF/next block start."""
         if self.current_token.type == TokenType.NEWLINE:
              self.consume(TokenType.NEWLINE)
         # Allow EOF or the start of the next block definition (@) as valid terminators.
         elif self.current_token.type not in (TokenType.EOF, TokenType.AT):
              # If it's not NEWLINE and not a valid block/file end, it's an error.
              self.error(f"Expected NEWLINE or EOF/Next Block {context}, but got {self.current_token.type}")

    # --- Helper to skip variable declaration lines (V1 strategy) ---
    def _skip_variable_declaration(self):
        """Skips an entire line assumed to be a variable declaration (e.g., 'int identifier')."""
        self.consume(TokenType.KEYWORD_INT) # Consume 'int'
        self.consume(TokenType.IDENTIFIER) # Consume variable name

        # Skip the rest of the tokens on the line until NEWLINE or EOF.
        # This handles simple declarations like 'int a' or assignments like 'int a = 10'.
        while self.current_token.type not in (TokenType.NEWLINE, TokenType.EOF):
             self.consume(self.current_token.type)

        # After skipping the line content, consume the terminating NEWLINE.
        if self.current_token.type == TokenType.NEWLINE:
             self.consume(TokenType.NEWLINE)

# --- Example Usage ---
if __name__ == "__main__":
    # Sample source code to parse.
    source = """@calculate:
    int a # Variable declaration (skipped by parser V1)
    int b # Another variable declaration
    a = 10 # An assignment statement
    b = a * 5 + 2
    print b # A print statement (treated as generic line)
    back # A back statement

@main: # Another block definition
    goto calculate # A goto statement
    # This is a comment after goto
    print main_done # Another generic line

@another_block:
    # Just a placeholder block
    back # Last statement

"""

    # Assumes claw_lexer.py is in the same directory or Python path.
    from claw_lexer import Lexer

    lexer = Lexer(source)
    tokens = lexer.tokenizer()

    # Optional: Print tokens for verification.
    print("--- Tokens ---")
    for token in tokens:
        print(token)
    print("------------")

    parser = Parser(tokens)
    try:
        ast_tree = parser.parse()

        # Print the generated AST using a simple recursive function.
        print("\n--- AST ---")
        def print_ast(node, indent=0):
            """Helper function to recursively print the AST structure."""
            print("  " * indent + f"- {type(node).__name__}", end="")
            if isinstance(node, Program):
                print(f" (blocks: {len(node.block_definitions)})")
                for block_def in node.block_definitions:
                    print_ast(block_def, indent + 1)
            elif isinstance(node, BlockDefinition):
                 print(f" (name: {node.name}, inner_content: {len(node.inner_content)})")
                 for content in node.inner_content:
                      print_ast(content, indent + 1)
            elif isinstance(node, GenericLineBlock):
                 # Show the reconstructed text from tokens for generic lines.
                 lexemes = [t.lexeme for t in node.line_tokens]
                 print(f" (tokens: {''.join(lexemes)!r})") # Use !r to show quotes clearly
            elif isinstance(node, GotoBlock):
                 print(f" (target: {node.target_block_name})")
            elif isinstance(node, BackBlock):
                 print() # Type name is sufficient
            else:
                 # Generic fallback for unknown node types.
                 print(f" (data: {vars(node)})")

        print_ast(ast_tree)
        print("------------")

    except SyntaxError as e:
        print(f"Parsing failed: {e}")
    except Exception as e:
         print(f"An unexpected error occurred during parsing: {e}")